# This Dockerfile is "injected" by the test util into the top directory of the repo.  Keep that in mind when examining the ADD command.
FROM debian
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y python git locales
RUN locale-gen C.UTF-8
ENV LANG C.UTF-8
RUN locale -a
