# This Dockerfile is "injected" by the test util into the top directory of the repo.  Keep that in mind when examining the ADD command.
FROM logankoester/archlinux
RUN pacman -Syyu --noconfirm python git
ADD ./ /root/subuser/
RUN /root/subuser/logic/subuser test
