#!/bin/bash
mkdir -p /home/travis/
cp -r $1/test/home/ /home/travis/test-home/
git config --system user.name "Your Name"
git config --system user.email you@example.com
cp -r $1/test/remote-test-repo/ /home/travis/remote-test-repo
cd /home/travis/remote-test-repo
git init
git add .
git commit -m 'test'
cp -r $1/test/default-test-repo/ /home/travis/default-test-repo
cd /home/travis/default-test-repo
git init
git add .
git commit -m 'test'
cp -r $1/test/version-constrained-test-repo/ /home/travis/version-constrained-test-repo
cd /home/travis/version-constrained-test-repo
git init
git add .
git commit -m 'test'
git checkout -b subuser-0.5
echo {} > .subuser.json
git mv bip bop
git add .
git commit -m 'change bip to bop'
git checkout master
git mv bip baz
bit add .
git commit -m 'change bop to baz'
cp -r  $1/test/local-test-repo-§€č /home/travis/local-test-repo-§€č
cp -r $1/test/hashtest/ /home/travis/hashtest/
echo User is $USER id $UID
echo ls -la /home/travis/hashtest
ls -la /home/travis/hashtest
chmod -R 644 /home/travis/hashtest
mkdir -p /home/travis/docker
echo "{}" > /home/travis/docker/images.json
