#!/bin/bash
mkdir -p /home/travis/
cp -r $1/test/home/ /home/travis/test-home/
git config --global user.name "Your Name"
git config --global user.email you@example.com
cp -r $1/test/remote-test-repo/ /home/travis/remote-test-repo
cd /home/travis/remote-test-repo
git init
git add .
git commit -m 'test'
cd /home/travis/test-home/.subuser/repositories/default
git init
git add .
git commit -m 'test'
