#!/usr/bin/env python
import shutil
import sys
import subprocess

shutil.copyfile("/usr/local/share/Elm-0.11/elm-runtime.js","./build/elm-runtime.js")

runtimeArg = ["--runtime=./build/elm-runtime.js"]

for arg in sys.argv:
 if arg.startswith("--runtime"):
  setRuntime = []

subprocess.call(["/usr/local/bin/elm"]+runtimeArg+sys.argv[1:])
