#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import subuserlib.registry
import subuserlib.permissions
import subuserlib.subprocessExtras

####################################################
def printHelp():
  print(""" Clean your system of unneeded images/libaries/executable-less programs.  If a libarary has no programs depending on it, uninstall that libarary.  Run this command with:

$ subuser clean
""")

def gatherUnneededLibs():
  """ Returns a list of unneeded libaries. """
  unneededLibs = []
  for program in subuserlib.registry.getInstalledPrograms():
    if not subuserlib.permissions.hasExecutable(program) and not subuserlib.registry.hasInstalledDependencies(program):
      unneededLibs.append(program)
  return unneededLibs

def cleanUnneededLibs():
  programsToUninstall = gatherUnneededLibs()
  if len(programsToUninstall) > 0:
    performUninstalls(programsToUninstall)
  else:
    print("Looks like your system is already clean.")

def performUninstalls(programsToUninstall):
  # Display the programs that will be uninstalled.
  print("The following programs will be uninstalled:")
  for program in programsToUninstall:
    print(program)
  # Ask the user if they want to continue.
  if raw_input("Continue [y/n]? ") == "y":
    # Preform the uninstallation.
    for program in programsToUninstall:
      subuserlib.subprocessExtras.subprocessCheckedCall(["subuser","uninstall",program])

#################################################################################################

# This command takes no arguments.
# If the user passed it one or more arguments,
# They cleary don't know what they're doing,
# and need to see the help message.
if len(sys.argv) > 1: 
  printHelp()
else:
  cleanUnneededLibs()
