#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import subuserlib.utils
import subuserlib.registry
import subuserlib.permissions

####################################################
def printHelp():
 print(""" Clean your system of unneeded images/libaries/executable-less programs.  If a libarary has no programs depending on it, uninstall that libarary.  Run this command with:

$ subuser clean
""")

def gatherUnneededLibs():
 """ Returns a list of unneeded libaries. """
 installedPrograms = subuserlib.registry.getRegistry()
 unneededLibs = []
 for program in installedPrograms.keys():
  if not subuserlib.permissions.hasExecutable(program) and not subuserlib.registry.hasInstalledDependencies(program):
   unneededLibs.append(program)
 return unneededLibs
 
def cleanUnneededLibs():
 programsToUninstall = gatherUnneededLibs()
 if len(programsToUninstall) > 0:
  performUninstalls(programsToUninstall)
 else:
  print("Looks like your system is already clean.")

def performUninstalls(programsToUninstall):
 print("The following programs will be uninstalled:")
 for program in programsToUninstall:
  print(program)
 if raw_input("Continue [y/n]? ") == "y":
  for program in programsToUninstall:
   subuserlib.utils.subprocessCheckedCall(["subuser","uninstall",program])
 
#################################################################################################
if len(sys.argv) > 1:
 printHelp()
else:
 cleanUnneededLibs() 
