#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import subuserlib.installTime

if len(sys.argv) == 1:
  print(subuserlib.installTime.currentTimeString())

else:
 print(""" Display the current time in properly formated utc.  Useful for setting the last-update-time attribute in permissions.json """)
