#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.

import sys
import subuserlib.run

##############################################################
def printHelp():
  print("""Display the command which would be issued to launch docker if you were to run this program.  For example:
$ subuser dry-run firefox

Please note, this is only a rough approximation for debugging purposes and there is no guarantee that the command displayed here would actually work.
""")

def getArgsToPassToProgram():
  if len(sys.argv) > 2:
    return sys.argv[2:]
  else:
    return []

#################################################################################################
if len(sys.argv) == 1 or {"help","-h","--help"} & set(sys.argv):
  printHelp()
  sys.exit()
#################################################################################################

programName = sys.argv[1]
subuserlib.run.runProgram(programName,getArgsToPassToProgram(),dry=True)
