#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.

import sys,optparse

import subuserlib.registry,subuserlib.dockerImages,subuserlib.subprocessExtras,subuserlib.commandLineArguments

####################################################
def parseCliArgs():
  usage = "usage: subuser %prog [options]"
  description = """ Install all of the programs that were installed on a previous system, given that you backed up the installed-programs.json file.

"""
  parser = optparse.OptionParser(usage=usage,description=description,formatter=subuserlib.commandLineArguments.HelpFormatterThatDoesntReformatDescription())
  advancedInstallOptions = subuserlib.commandLineArguments.advancedInstallOptionsGroup(parser)
  parser.add_option_group(advancedInstallOptions)
  return parser.parse_args()

def resetRegistry():
  """ Go through registry and unregister any program that is not actually installed. """
  for program in subuserlib.registry.getInstalledPrograms():
    if not subuserlib.dockerImages.isProgramsImageInstalled(program):
      subuserlib.registry.unregisterProgram(program)

def installFromRegistry(useCache):
  """ Installs all of the programs listed in installed-programs.json file. """
  resetRegistry()
  for program in subuserlib.registry.getInstalledPrograms():
    print("\n=== Installing <%s> from installed-programs.json registry....\n" % program)
    if useCache:
      subuserlib.subprocessExtras.subprocessCheckedCall(["subuser","install",program,"--from-cache"])
    else:
      subuserlib.subprocessExtras.subprocessCheckedCall(["subuser","install",program])

#################################################################################################

options,arguments=parseCliArgs()
installFromRegistry(options.useCache)
