#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import subuserlib.utils
import subuserlib.registry
import subuserlib.paths

def printHelp():
 print("""You can either list programs availiable for instalation with:
 $ subuser list available

Or you can list installed programs with:
 $ subuser list installed
""")

if len(sys.argv) == 1:
 printHelp()

elif sys.argv[1] == "available":
 availableProgramsPath = subuserlib.paths.getAvailableProgramsPath()
 subuserlib.utils.subprocessCheckedCall(["ls",availableProgramsPath])

elif sys.argv[1] == "installed":
 installedPrograms = subuserlib.registry.getInstalledPrograms()
 for program, version in installedPrograms.iteritems():
  print(program)

else:
 printHelp()
