#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import subuserlib.installTime
import subuserlib.permissions
import subuserlib.availablePrograms
import subuserlib.paths

def printHelp():
 print("""
Mark a program as needing to be updated.  Note, that this may mess up the formatting of it's permissions.json file.

Usage:
$ subuser mark-as-needing-update program-name
""")

#################################################################################################
if len(sys.argv) == 1 or sys.argv[1] == "help" or sys.argv[1] == "-h" or sys.argv[1] == "--help":
 printHelp()
 sys.exit()
#################################################################################################

programName = sys.argv[1] 
# CheckFeedback: is the program in subuser available? If not exit.
subuserlib.utils.checkExitNoneAvailableProgram(programName, "Cannot mark it as having an update.")

permissions = subuserlib.permissions.getPermissions(programName)
permissions["last-update-time"] = subuserlib.installTime.currentTimeString()
subuserlib.permissions.setPermissions(programName,permissions)
