#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import optparse
import subuserlib.installTime
import subuserlib.commandLineArguments

def parseCliArgs():
  usage = "usage: subuser %prog PROGRAM_NAME(s)"
  description = """
Mark a program as needing to be updated.  Note, that this may mess up the formatting of it's permissions.json file.

Usage:
$ subuser mark-as-needing-update program-name
"""
  parser=optparse.OptionParser(usage=usage,description=description,formatter=subuserlib.commandLineArguments.HelpFormatterThatDoesntReformatDescription())
  return parser.parse_args()

#################################################################################################

options,programNames = parseCliArgs()

for program in programNames:
  subuserlib.installTime.markProgramAsNeedingUpdate(program)