#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import subuserlib.registry
import subuserlib.availablePrograms

def printHelp():
  print("""print an extended dependency matrix:
  OPTION: names:  program-names (also multiple): print a dependency-matrix for program names
    $ subuser print-dependency-matrix firefox vim xterm

  Option: --available: print a dependency-matrix for programs available
    $ subuser print-dependency-matrix --available

  Option: --installed: print a dependency-matrix for programs available
    $ subuser print-dependency-matrix --installed
""")

#################################################################################################
if len(sys.argv) == 1 or sys.argv[1] == "help" or sys.argv[1] == "-h" or sys.argv[1] == "--help":
  printHelp()
  sys.exit()
#################################################################################################

commandOptionList = ['--available', '--installed']
userProgramList, userOptionList = subuserlib.utils.getUserCommandLine(sys.argv[1:], commandOptionList)

#Check exclusive commands
if '--available' in userOptionList and '--installed' in userOptionList:
  print("\nEXCLUSIVE-OPTION-ERROR: you can not use these options together:")
  exclusiveCommandOption = ["--available", "--installed"]
  print(subuserlib.utils.getExclusiveCommandOptionText(exclusiveCommandOption, addNewLine=True, indentSpaces=3))
  sys.exit()
  
if '--available' in userOptionList:
  userProgramList = subuserlib.availablePrograms.getAvailablePrograms()
elif '--installed' in userOptionList:
  #use this in case the user specified also some program names plus --installed
  userProgramList = list(set(userProgramList + subuserlib.registry.getInstalledPrograms())) 

dependencyMatrix = subuserlib.registry.getDependencyMatrix(userProgramList, useHasExecutable=False, sortLists=True)
print("\n===== DEPENDENCY MATRIX =====\n")
for programMain in dependencyMatrix.keys():
  print("<%s>:" % programMain)
  print("    required-by: %s" % dependencyMatrix[programMain]["required-by"])
  print("    depends-on: %s" % dependencyMatrix[programMain]["depends-on"])
