#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import optparse
import subuserlib.registry
import subuserlib.commandLineArguments

def parseCliArgs():
  usage = "usage: subuser %prog PROGRAM_NAME(s)"
  description = """Prints the dependency trees of subuser programs:
  $ subuser dependency-tree firefox vim xterm
"""
  parser = optparse.OptionParser(usage=usage,description=description,formatter=subuserlib.commandLineArguments.HelpFormatterThatDoesntReformatDescription())
  return parser.parse_args()


#################################################################################################

options,programList = parseCliArgs()

print("\n===== DEPENDENCY TREE =====\n")
for programMain in programList:
  treeString = ''
  for index, dependency in enumerate(subuserlib.registry.getDependencyTree(programMain)):
    if index > 0:
      treeString = ''.join([treeString, '  ' * index, '|__', dependency, '\n'])
    else:
      treeString = ''.join([treeString, dependency, '\n'])

  print treeString
