#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import subuserlib.registry
import subuserlib.availablePrograms

def printHelp():
  print("""print an extended dependency matrix:
  OPTION: names:  program-names (also multiple): print a dependency-matrix for program names
    $ subuser print-dependency-matrix firefox vim xterm

  Option: --available: print a dependency-matrix for programs available
    $ subuser print-dependency-matrix --available

  Option: --installed: print a dependency-matrix for programs available
    $ subuser print-dependency-matrix --installed
""")

def printDependencyMatrices(programs):
  dependencyMatrix = subuserlib.registry.getDependencyMatrix(programs, useHasExecutable=False, sortLists=True)
  print("\n===== DEPENDENCY MATRIX =====\n")
  for programMain in dependencyMatrix.keys():
    print("<%s>:" % programMain)
    print("    required-by: %s" % dependencyMatrix[programMain]["required-by"])
    print("    depends-on: %s" % dependencyMatrix[programMain]["depends-on"])

#################################################################################################
if len(sys.argv) == 1 or sys.argv[1] == "help" or sys.argv[1] == "-h" or sys.argv[1] == "--help":
  printHelp()
  sys.exit()
#################################################################################################

commandOptionList = ['--available', '--installed']
userProgramList, userOptionList = subuserlib.utils.parseCommandLineArgs(sys.argv[1:], commandOptionList)

  
if '--available' in userOptionList:
  print("Dependency matrices for programs that are available for instalation:")
  printDependencyMatrices(subuserlib.availablePrograms.getAvailablePrograms())

if '--installed' in userOptionList:
  print("Dependency matrices for installed programs:")
  printDependencyMatrices(subuserlib.registry.getInstalledPrograms())

if len(userProgramList) > 0:
 print("Interdependencies between specified programs:")
 printDependencyMatrices(userProgramList)
