#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import subprocess
import os
import subuserlib.paths
import subuserlib.registry
#######################################################
programName = sys.argv[1]
#######################################################
def printHelp():
 print("Issue the `subuser uninstall program-name` command to uninstall a program. NOTE: this operation does not remove that program's home directory.")

def uninstall(programName):
 subprocess.call(["docker","rmi","subuser-"+programName])
 if os.path.exists(subuserlib.paths.getExecutablePath(programName)):
  os.remove(subuserlib.paths.getExecutablePath(programName))

 subuserlib.registry.unregisterProgram(programName)
 print("The program has been uninstalled but it's home directory remains:")
 programHomeDir=subuserlib.paths.getProgramHomeDirOnHost(programName)
 print(programHomeDir)

#######################################################

if programName == "--help" or programName == "-h":
 printHelp()
elif not subuserlib.registry.isProgramInstalled(programName):
 print("Could not uninstall "+programName+" program is not installed.")
 printHelp()
else:
 uninstall(programName)
