#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import subprocess
import os

home = os.path.expanduser("~")

def printHelp():
 print("You can use one of the following commands:")
 subprocess.call(["ls",os.path.join(home,"subuser/logic/subuser-commands")])

if sys.argv[1] == "help" or sys.argv[1] == "--help" or sys.argv[1] == "-h":
 printHelp()
 exit()

utilityPath = os.path.join(home,"subuser","logic","subuser-commands",sys.argv[1])

if not os.path.exists(utilityPath):
 print("Command not found:"+sys.argv[1])
 printHelp()
 exit()
 
subprocess.call([utilityPath]+sys.argv[2:])
