#!/usr/bin/env python
# This file should be compatible with both Python 2 and 3.
# If it is not, please file a bug report.
import sys
import os
import subprocess
import subuserCommands.subuserlib.commands

def printHelp():
  print("You can use one of the following commands:")
  for command in subuserCommands.subuserlib.commands.getSubuserCommands():
    print(command)
  print("for more info about each option use: subuser <option> -h")

if len(sys.argv) < 2 or sys.argv[1] == "help" or sys.argv[1] == "--help" or sys.argv[1] == "-h":
  printHelp()
  exit()

commandExecutablePath = subuserCommands.subuserlib.commands.getSubuserCommandPath(sys.argv[1])

if not commandExecutablePath:
  print("Command not found: "+sys.argv[1])
  printHelp()
  sys.exit(1)

subprocess.call([commandExecutablePath]+sys.argv[2:])
